name: Build w64devkit

on:
  pull_request: {}
  push:
    branches:
      - '*'
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        arch: ["x64"]
        flavor: ["", "fortran", "mini"]

    steps:
      - uses: actions/checkout@v3

      - name: Apply Fortran patch
        if: matrix.flavor == 'fortran'
        run: patch -p1 -i src/variant-fortran.patch

      - name: Apply Mini patch
        if: matrix.flavor == 'mini'
        run: patch -p1 -i src/variant-mini.patch

      - name: Generate ZIP name and version string
        id: filename
        env:
          ARCH: ${{ matrix.arch }}
          FLAVOR: ${{ matrix.flavor }}
        run: |
          GIT_VERSION="$(git describe --tags --always)"
          echo "version=${GIT_VERSION:1}" >> $GITHUB_OUTPUT
          echo "zipname=w64devkit${ARCH:+-$ARCH}${FLAVOR:+-$FLAVOR}-${GIT_VERSION:1}" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          docker build -t w64devkit .
          docker run --rm w64devkit > ${{ steps.filename.outputs.zipname }}.zip

      - name: Delete existing release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete ${{ steps.filename.outputs.version }} --yes || true

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.filename.outputs.version }}
          files: ${{ steps.filename.outputs.zipname }}.zip
          draft: true
