name: Build w64devkit

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate archive name and version string
        id: filename
        run: |
          VER="$(git describe --tags --always | tr v -)"
          echo "version=${VER#v}" >> $GITHUB_OUTPUT
          echo "archive=w64devkit-${VER#v}" >> $GITHUB_OUTPUT

      - name: Build and export artifact
        run: |
          docker build \
            --output type=local,dest=out \
            .
          ls -lh out

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.filename.outputs.archive }}
          path: out/*.exe

      - name: Delete existing release (if any)
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete ${{ steps.filename.outputs.version }} --yes || true
          git push origin :refs/tags/${{ steps.filename.outputs.version }} || true

      - name: Create new release
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.filename.outputs.version }}
          name: w64devkit-${{ steps.filename.outputs.version }}
          files: out/*.exe
