name: Build w64devkit

on:
  pull_request: {}
  push:
    branches:
      - '*'
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        arch: ["x64"]

    steps:
      - uses: actions/checkout@v4

      - name: Generate archive name and version string
        id: filename
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          GIT_VERSION="$(git describe --tags --always)"
          echo "version=${GIT_VERSION:1}" >> $GITHUB_OUTPUT
          echo "archive=w64devkit-$ARCH-${GIT_VERSION:1}" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          docker build -t w64devkit .
          docker run --rm w64devkit > ${{ steps.filename.outputs.archive }}.exe

      - name: Delete existing tag and release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          if gh release view "$TAG_NAME" >/dev/null 2>&1; then
            echo "Release $TAG_NAME exists — deleting it..."
            gh release delete "$TAG_NAME" -y
          fi
          git push origin ":refs/tags/$TAG_NAME" || true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.filename.outputs.version }}
          files: w64devkit-*.exe
          draft: true
