name: Build w64devkit

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x64, x86]

    steps:
      - uses: actions/checkout@v4

      - name: Generate version string
        id: version
        run: |
          VER="$(git describe --tags --always | tr v -)"
          echo "ver=${VER#v}" >> $GITHUB_OUTPUT

      - name: Build with Docker
        run: |
          docker build --build-arg ARCH=${{ matrix.arch }} -t w64devkit-${{ matrix.arch }} .

      - name: Extract files
        run: |
          id=$(docker create w64devkit-${{ matrix.arch }})
          docker cp $id:/w64devkit ./out
          docker rm $id

      - name: Compress artifact
        run: |
          7z a w64devkit-${{ matrix.arch }}-${{ steps.version.outputs.ver }}.7z ./out/*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: w64devkit-${{ matrix.arch }}
          path: w64devkit-${{ matrix.arch }}-${{ steps.version.outputs.ver }}.7z

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Delete existing release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete ${{ needs.build.outputs.ver }} --yes || true
          git push origin :refs/tags/${{ needs.build.outputs.ver }} || true

      - name: Create new release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.build.outputs.ver }}
          name: w64devkit-${{ needs.build.outputs.ver }}
          files: artifacts/**/*
